name: First Workflow
on: 
  pull_request:
    types: [opened, synchronize, reopened]
  
  workflow_dispatch:
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello World!"
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: cat test.txt

