name: Issue Event Handler

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
permissions:
  issues: write
  
jobs:
  handle_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Print issue details
        if: github.event_name == 'issues'
        run: |
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Author: ${{ github.event.issue.user.login }}"
          echo "Issue Body: ${{ github.event.issue.body }}"
      - name: Determine label based on title
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
        run: |
          LABEL=""
          
          # Assign labels based on keywords in the title
          if [[ "$ISSUE_TITLE" == *"python"* ]]; then
            LABEL="python_fix"
          elif [[ "$ISSUE_TITLE" == *"feature"* ]]; then
            LABEL="enhancement"
          elif [[ "$ISSUE_TITLE" == *"urgent"* ]]; then
            LABEL="priority"
          fi

          # Apply label if one was determined
          if [[ -n "$LABEL" ]]; then
            echo "Assigning label: $LABEL"
            echo "LABEL=$LABEL" >> $GITHUB_ENV
          else
            echo "No matching label found."
          fi

      - name: Apply label to the issue
        if: env.LABEL != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          REPO=${{ github.repository }}
          LABEL=${{ env.LABEL }}

          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/$REPO/issues/$ISSUE_NUMBER/labels \
               -d "{\"labels\": [\"$LABEL\"]}"

      - name: Print comment details
        if: github.event_name == 'issue_comment'
        run: |
          echo "Comment Author: ${{ github.event.comment.user.login }}"
          echo "Comment Body: ${{ github.event.comment.body }}"

      - name: Close issue if comment contains 'working' or 'completed'
        if: github.event_name == 'issue_comment' && contains(github.event.comment.body, 'working') || contains(github.event.comment.body, 'completed')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          REPO=${{ github.repository }}

          echo "Adding comment before closing issue #$ISSUE_NUMBER in $REPO"

          # Add a comment to the issue
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/$REPO/issues/$ISSUE_NUMBER/comments \
               -d '{"body": "This issue is being closed automatically as the comment contains a completion keyword."}'

          echo "Closing issue #$ISSUE_NUMBER"

          # Close the issue
          curl -X PATCH -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/$REPO/issues/$ISSUE_NUMBER \
               -d '{"state": "closed"}'
